name: Code Quality

on:
  push:
    branches: [ main, develop, "claude/**" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black mypy pylint

    - name: Run Black (Code Formatter Check)
      run: |
        echo "🎨 Checking code formatting with Black..."
        black --check --diff . || true
      continue-on-error: true

    - name: Run Flake8 (Linting)
      run: |
        echo "🔍 Running Flake8 linter..."
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true

    - name: Run MyPy (Type Checking)
      run: |
        echo "🔍 Running MyPy type checker..."
        mypy --install-types --non-interactive . || true
      continue-on-error: true

    - name: Run Pylint
      run: |
        echo "🔍 Running Pylint..."
        pylint **/*.py --exit-zero --disable=C,R --max-line-length=127 || true
      continue-on-error: true

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: moderate
